apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: big-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: local/streamlit:latest
        ports:
        - containerPort: 8501
